### ISSUE TITLE
About data download

### ISSUE THREAD

**Issue by HarryHsing** [aharley/pips#13]
Hi, the download speed of training data via torrent is very very slow (10KB/s), I wonder if there is an alternative way to download the training data.

`(RGB images (cleanpass), Optical flow, and Object segmentation).`

Thank you very much for your support!

**Comment by aharley** [comment]
I uploaded trajectories and object masks (for flyingthings++) here, which should allow you to skip the optical flow part at least: 
https://drive.google.com/drive/folders/1zzWkGGFgJPyHpVaSA19zpYlux1Mf6wGC?usp=share_link
I haven't put the RGB there yet, because I assumed the torrent is still doing OK. Sometimes you need to leave it overnight, and then there's a burst of fast speeds at a random hour. Can you let me know again soon, if you are still stuck?

**Comment by HarryHsing** [comment]
> I uploaded trajectories and object masks (for flyingthings++) here, which should allow you to skip the optical flow part at least: 
> 
> https://drive.google.com/drive/folders/1zzWkGGFgJPyHpVaSA19zpYlux1Mf6wGC?usp=share_link
> 
> I haven't put the RGB there yet, because I assumed the torrent is still doing OK. Sometimes you need to leave it overnight, and then there's a burst of fast speeds at a random hour. Can you let me know again soon, if you are still stuck?

Thanks a lot for your prompt reply!
Yes, currently I am still stuck at downloading the rgb data.

**Comment by HarryHsing** [comment]
I tried different methods, but it seems that the torrent of "RGB images (cleanpass)" is not working.
