### ISSUE TITLE
Evaluation Code for KITTI

### ISSUE THREAD

**Issue by wkbian** [aharley/pips#27]
Hi @aharley ,

Your paper PIPS is excellent! But I encountered some issues when reimplementing your paper. I was trying to evaluate PIPS on KITTI (as mentioned in your paper), but I cannot find related code in this repository. Would you please release the script or give us some necessary guidance? Thanks!

**Comment by aharley** [comment]
Thanks for the message about this. I just want to acknowledge that this is an issue and I will work on it soon, since you're asking for it. 

The basic idea is to create 8-frame trajectories using projected 3D coordinates of box centers in the "tracking" subset of KITTI. 

The code for this part still needs to be cleaned up, and also it is probably not a very clean evaluation in general, because the "3D center" trajectories do not correspond to the trajectory of an actual surface point.

**Comment by wkbian** [comment]
Thanks for your reply! There is another issue. I tried many configurations: the default config in train.py, the config you mentioned in the paper, and I also try to increase the batch size, model capacity, but I cannot reimplement the numbers your reported on the DAVIS dataset in the paper. Do you have any suggestions?

**Comment by aharley** [comment]
Have you been able to run the pre-trained model and reproduce the numbers shown in the repo readme?

**Comment by wkbian** [comment]
Yes! Your released model outperforms the numbers you report in the paper! However, I can not reproduce either the released model or the performance you report in the paper.  The released model performance on CroHD: ate_vis=4.56, ate_occ=7.71, and on DAVIS: 63.6. The best performance we produce is CroH: ate_vis=4.68, ate_occ=8.03, and DAVIS: 61.8. The training parameters are: B=4, S=8, N=128, lr=5e-4, step=200000.
