### ISSUE TITLE
Trajectories

### ISSUE THREAD

**Issue by ozgurkara99** [aharley/pips#35]
Hello,

I am working on the project and would like to use the trajectories for Flyingthings++. Since the optical_flow folder in the dataset needs 600 GB of storage to generate 80 GB trajectories, could you please upload the trajectories folder and share the link so that I can directly download it as well just to do the evaluation under the same settings?

Thank you
Ozgur

**Comment by aharley** [comment]
Yes, we provide a link for this in the readme. Here it is again: 
https://drive.google.com/drive/u/2/folders/1zzWkGGFgJPyHpVaSA19zpYlux1Mf6wGC

**Comment by ozgurkara99** [comment]
ah thank you a lot.

**Comment by muqiu791** [comment]
Hello, I would like to ask why after I downloaded flyingthings++ from this link, executing train.py still reports an error:
`FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.`
`FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/pips/data/flyingthings/object_index/TRAIN/C/0582/right/0007.pfm'`

"flyingthings/object_index"
Can I not download this 600G file? Because it downloads slowly.
